### ISSUE TITLE
update `swc_ecma_transforms_proposal` to `v0.167.15`

### ISSUE THREAD

**Issue by tjjfvi** [denoland/deno_ast#160]
This version fixes https://github.com/swc-project/swc/issues/8020, which currently causes incorrect `ReferenceError`s in Deno:

```ts
// foo.ts

using foo = null

const bar = 1

console.log(baz()) // should log `1`

function baz() {
  return bar
}
```
```
$ deno run foo.ts
error: Uncaught ReferenceError: bar is not defined
  return bar
  ^
    at baz (file://.../foo.ts:8:3)
    at file://.../foo.ts:5:13
```

**Comment by dsherret** [comment]
I'm going to do it tomorrow probably. There were a bunch of other fixes that have landed now.
